export enum PostActionType {
  POST_CREATED = 'POST_CREATED',
  POST_DELETED = 'POST_DELETED',
  POST_VIEWED = 'POST_VIEWED',
  POST_DUPLICATED = 'POST_DUPLICATED',
  POST_TITLE_CHANGED = 'POST_TITLE_CHANGED',
  POST_DESCRIPTION_CHANGED = 'POST_DESCRIPTION_CHANGED',
  POST_STATUS_CHANGED = 'POST_STATUS_CHANGED',
}